#! /usr/bin/env python

import re
import sys
import os

from tools.file_utils import find_functions


def main(target):

    with open(target, "r") as header_file:
        data = header_file.readlines()

    functions = find_functions(data)

    cpp_target = target.replace(".h", ".cpp")

    with open(cpp_target, "a") as cpp_file:
        for function in functions:
            print(function.empty_implementation, file=cpp_file, end="\n\n")


if __name__ == "__main__":
    targets = sys.argv[1:]
    for path in targets:
        if ".h" not in path:
            path += ".h"

        main(path)